In [3]:
import pandas as pd
import numpy as np

mydata= pd.read_csv('C://Users//Gautam Ruikar//Downloads//FinalData.csv')
display(mydata)

,ID,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditorDisplayName,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate
0,927358.0,1,927386.0,NaN,29-05-2009 18:09,NaN,23348,10062790,<p>I accidentally <strong>committed the wrong ...,89904,...,NaN,30-06-2021 05:07,05-10-2021 13:26,How do I undo the most recent local commits in...,<git><version-control><git-commit><undo>,98,10,7322.0,NaN,16-03-2013 10:08
1,2003505.0,1,2003515.0,NaN,05-01-2010 01:12,NaN,18514,9285139,<p>I want to delete a branch both locally and ...,95592,...,NaN,06-10-2021 22:38,06-10-2021 22:38,How do I delete a Git branch locally and remot...,<git><version-control><git-branch><git-push><g...,41,10,5727.0,NaN,NaN
2,5767325.0,1,5767357.0,NaN,23-04-2011 22:17,NaN,9931,8937271,<p>I have an array of numbers and I'm using th...,364969,...,NaN,21-05-2020 04:20,24-09-2021 08:51,How can I remove a specific item from an array?,<javascript><arrays>,112,5,1507.0,NaN,NaN
3,16956810.0,1,16957078.0,NaN,06-06-2013 08:06,NaN,6304,8229811,<p>I'm trying to find a way to scan my entire ...,954986,...,NaN,21-05-2017 11:40,30-08-2021 13:56,How do I find all files containing specific te...,<linux><text><grep><directory><find>,53,10,3036.0,NaN,NaN
4,2906582.0,1,2906586.0,NaN,25-05-2010 16:39,NaN,2306,7805008,<p>I would like to create an HTML button that ...,48523,...,NaN,21-04-2021 16:46,22-09-2021 19:42,How to create an HTML button that acts like a ...,<html><button><hyperlink><anchor>,37,9,503.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199996,52253192.0,1,52264568.0,NaN,10-09-2018 07:44,NaN,6,40455,"\n<p>I am currently trying to figure out, how ...",6333935,...,NaN,10-09-2018 19:55,16-12-2020 15:47,PySpark - to_date format from column,<apache-spark><pyspark><apache-spark-sql>,3,0,1.0,NaN,NaN
199997,26151.0,1,26162.0,NaN,25-08-2008 14:47,NaN,73,40455,<p>C++ 0x has template aliases (sometimes refe...,2759,...,Konrad Rudolph,07-08-2012 15:11,02-09-2015 04:27,Template typedefs - What's your work around?,<c++><templates><type-safety>,3,1,19.0,NaN,NaN
199998,37141516.0,1,55449823.0,NaN,10-05-2016 14:31,NaN,22,40454,"<p>Laravel 5.2 has pretty nice Helpers, I woul...",4322159,...,NaN,NaN,28-09-2021 11:07,Laravel 5.2 pluck() multiple attributes from E...,<laravel-5.2><helpers><laravel-collection>,9,0,4.0,NaN,NaN
199999,12005526.0,1,22312983.0,NaN,17-08-2012 12:10,NaN,16,40454,<p>I was given access to a server with 50+ php...,1382299,...,NaN,08-11-2016 18:11,05-04-2020 20:11,Erase multiple packages using rpm or yum,<unix><rpm><yum>,5,0,9.0,NaN,NaN
200000,11041961.0,1,NaN,NaN,14-06-2012 22:00,NaN,18,40454,<p>I tried mongo import like this </p>\n<li><c...,1052073,...,NaN,NaN,11-04-2020 19:58,Cannot import mongodb,<mongodb><import>,7,1,3.0,NaN,NaN

In [8]:
mydata['Body'] = mydata['Body'].str.strip('<p>')
display(mydata)

,ID,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditorDisplayName,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate
0,927358.0,1,927386.0,NaN,29-05-2009 18:09,NaN,23348,10062790,I accidentally <strong>committed the wrong fil...,89904,...,NaN,30-06-2021 05:07,05-10-2021 13:26,How do I undo the most recent local commits in...,<git><version-control><git-commit><undo>,98,10,7322.0,NaN,16-03-2013 10:08
1,2003505.0,1,2003515.0,NaN,05-01-2010 01:12,NaN,18514,9285139,I want to delete a branch both locally and rem...,95592,...,NaN,06-10-2021 22:38,06-10-2021 22:38,How do I delete a Git branch locally and remot...,<git><version-control><git-branch><git-push><g...,41,10,5727.0,NaN,NaN
2,5767325.0,1,5767357.0,NaN,23-04-2011 22:17,NaN,9931,8937271,I have an array of numbers and I'm using the <...,364969,...,NaN,21-05-2020 04:20,24-09-2021 08:51,How can I remove a specific item from an array?,<javascript><arrays>,112,5,1507.0,NaN,NaN
3,16956810.0,1,16957078.0,NaN,06-06-2013 08:06,NaN,6304,8229811,I'm trying to find a way to scan my entire Lin...,954986,...,NaN,21-05-2017 11:40,30-08-2021 13:56,How do I find all files containing specific te...,<linux><text><grep><directory><find>,53,10,3036.0,NaN,NaN
4,2906582.0,1,2906586.0,NaN,25-05-2010 16:39,NaN,2306,7805008,I would like to create an HTML button that act...,48523,...,NaN,21-04-2021 16:46,22-09-2021 19:42,How to create an HTML button that acts like a ...,<html><button><hyperlink><anchor>,37,9,503.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199996,52253192.0,1,52264568.0,NaN,10-09-2018 07:44,NaN,6,40455,"\n<p>I am currently trying to figure out, how ...",6333935,...,NaN,10-09-2018 19:55,16-12-2020 15:47,PySpark - to_date format from column,<apache-spark><pyspark><apache-spark-sql>,3,0,1.0,NaN,NaN
199997,26151.0,1,26162.0,NaN,25-08-2008 14:47,NaN,73,40455,C++ 0x has template aliases (sometimes referre...,2759,...,Konrad Rudolph,07-08-2012 15:11,02-09-2015 04:27,Template typedefs - What's your work around?,<c++><templates><type-safety>,3,1,19.0,NaN,NaN
199998,37141516.0,1,55449823.0,NaN,10-05-2016 14:31,NaN,22,40454,"Laravel 5.2 has pretty nice Helpers, I would l...",4322159,...,NaN,NaN,28-09-2021 11:07,Laravel 5.2 pluck() multiple attributes from E...,<laravel-5.2><helpers><laravel-collection>,9,0,4.0,NaN,NaN
199999,12005526.0,1,22312983.0,NaN,17-08-2012 12:10,NaN,16,40454,I was given access to a server with 50+ php rp...,1382299,...,NaN,08-11-2016 18:11,05-04-2020 20:11,Erase multiple packages using rpm or yum,<unix><rpm><yum>,5,0,9.0,NaN,NaN
200000,11041961.0,1,NaN,NaN,14-06-2012 22:00,NaN,18,40454,I tried mongo import like this </p>\n<li><code...,1052073,...,NaN,NaN,11-04-2020 19:58,Cannot import mongodb,<mongodb><import>,7,1,3.0,NaN,NaN

In [9]:

mydata['Body'] = mydata['Body'].str.strip('""')
display(mydata)

,ID,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditorDisplayName,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate
0,927358.0,1,927386.0,NaN,29-05-2009 18:09,NaN,23348,10062790,I accidentally <strong>committed the wrong fil...,89904,...,NaN,30-06-2021 05:07,05-10-2021 13:26,How do I undo the most recent local commits in...,<git><version-control><git-commit><undo>,98,10,7322.0,NaN,16-03-2013 10:08
1,2003505.0,1,2003515.0,NaN,05-01-2010 01:12,NaN,18514,9285139,I want to delete a branch both locally and rem...,95592,...,NaN,06-10-2021 22:38,06-10-2021 22:38,How do I delete a Git branch locally and remot...,<git><version-control><git-branch><git-push><g...,41,10,5727.0,NaN,NaN
2,5767325.0,1,5767357.0,NaN,23-04-2011 22:17,NaN,9931,8937271,I have an array of numbers and I'm using the <...,364969,...,NaN,21-05-2020 04:20,24-09-2021 08:51,How can I remove a specific item from an array?,<javascript><arrays>,112,5,1507.0,NaN,NaN
3,16956810.0,1,16957078.0,NaN,06-06-2013 08:06,NaN,6304,8229811,I'm trying to find a way to scan my entire Lin...,954986,...,NaN,21-05-2017 11:40,30-08-2021 13:56,How do I find all files containing specific te...,<linux><text><grep><directory><find>,53,10,3036.0,NaN,NaN
4,2906582.0,1,2906586.0,NaN,25-05-2010 16:39,NaN,2306,7805008,I would like to create an HTML button that act...,48523,...,NaN,21-04-2021 16:46,22-09-2021 19:42,How to create an HTML button that acts like a ...,<html><button><hyperlink><anchor>,37,9,503.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199996,52253192.0,1,52264568.0,NaN,10-09-2018 07:44,NaN,6,40455,"\n<p>I am currently trying to figure out, how ...",6333935,...,NaN,10-09-2018 19:55,16-12-2020 15:47,PySpark - to_date format from column,<apache-spark><pyspark><apache-spark-sql>,3,0,1.0,NaN,NaN
199997,26151.0,1,26162.0,NaN,25-08-2008 14:47,NaN,73,40455,C++ 0x has template aliases (sometimes referre...,2759,...,Konrad Rudolph,07-08-2012 15:11,02-09-2015 04:27,Template typedefs - What's your work around?,<c++><templates><type-safety>,3,1,19.0,NaN,NaN
199998,37141516.0,1,55449823.0,NaN,10-05-2016 14:31,NaN,22,40454,"Laravel 5.2 has pretty nice Helpers, I would l...",4322159,...,NaN,NaN,28-09-2021 11:07,Laravel 5.2 pluck() multiple attributes from E...,<laravel-5.2><helpers><laravel-collection>,9,0,4.0,NaN,NaN
199999,12005526.0,1,22312983.0,NaN,17-08-2012 12:10,NaN,16,40454,I was given access to a server with 50+ php rp...,1382299,...,NaN,08-11-2016 18:11,05-04-2020 20:11,Erase multiple packages using rpm or yum,<unix><rpm><yum>,5,0,9.0,NaN,NaN
200000,11041961.0,1,NaN,NaN,14-06-2012 22:00,NaN,18,40454,I tried mongo import like this </p>\n<li><code...,1052073,...,NaN,NaN,11-04-2020 19:58,Cannot import mongodb,<mongodb><import>,7,1,3.0,NaN,NaN

In [19]:

mydata['Body'] = mydata['Body'].str.strip(' ')
display(mydata)

,ID,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditorDisplayName,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate
0,927358.0,1,927386.0,NaN,29-05-2009 18:09,NaN,23348,10062790,I accidentally strongcommitted the wrong files...,89904,...,NaN,30-06-2021 05:07,05-10-2021 13:26,How do I undo the most recent local commits in...,<git><version-control><git-commit><undo>,98,10,7322.0,NaN,16-03-2013 10:08
1,2003505.0,1,2003515.0,NaN,05-01-2010 01:12,NaN,18514,9285139,I want to delete a branch both locally and rem...,95592,...,NaN,06-10-2021 22:38,06-10-2021 22:38,How do I delete a Git branch locally and remot...,<git><version-control><git-branch><git-push><g...,41,10,5727.0,NaN,NaN
2,5767325.0,1,5767357.0,NaN,23-04-2011 22:17,NaN,9931,8937271,I have an array of numbers and I'm using the c...,364969,...,NaN,21-05-2020 04:20,24-09-2021 08:51,How can I remove a specific item from an array?,<javascript><arrays>,112,5,1507.0,NaN,NaN
3,16956810.0,1,16957078.0,NaN,06-06-2013 08:06,NaN,6304,8229811,I'm trying to find a way to scan my entire Lin...,954986,...,NaN,21-05-2017 11:40,30-08-2021 13:56,How do I find all files containing specific te...,<linux><text><grep><directory><find>,53,10,3036.0,NaN,NaN
4,2906582.0,1,2906586.0,NaN,25-05-2010 16:39,NaN,2306,7805008,I would like to create an HTML button that act...,48523,...,NaN,21-04-2021 16:46,22-09-2021 19:42,How to create an HTML button that acts like a ...,<html><button><hyperlink><anchor>,37,9,503.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199996,52253192.0,1,52264568.0,NaN,10-09-2018 07:44,NaN,6,40455,"I am currently trying to figure out, how to pa...",6333935,...,NaN,10-09-2018 19:55,16-12-2020 15:47,PySpark - to_date format from column,<apache-spark><pyspark><apache-spark-sql>,3,0,1.0,NaN,NaN
199997,26151.0,1,26162.0,NaN,25-08-2008 14:47,NaN,73,40455,C++ 0x has template aliases (sometimes referre...,2759,...,Konrad Rudolph,07-08-2012 15:11,02-09-2015 04:27,Template typedefs - What's your work around?,<c++><templates><type-safety>,3,1,19.0,NaN,NaN
199998,37141516.0,1,55449823.0,NaN,10-05-2016 14:31,NaN,22,40454,"Laravel 5.2 has pretty nice Helpers, I would l...",4322159,...,NaN,NaN,28-09-2021 11:07,Laravel 5.2 pluck() multiple attributes from E...,<laravel-5.2><helpers><laravel-collection>,9,0,4.0,NaN,NaN
199999,12005526.0,1,22312983.0,NaN,17-08-2012 12:10,NaN,16,40454,I was given access to a server with 50+ php rp...,1382299,...,NaN,08-11-2016 18:11,05-04-2020 20:11,Erase multiple packages using rpm or yum,<unix><rpm><yum>,5,0,9.0,NaN,NaN
200000,11041961.0,1,NaN,NaN,14-06-2012 22:00,NaN,18,40454,I tried mongo import like this licodemongoimpo...,1052073,...,NaN,NaN,11-04-2020 19:58,Cannot import mongodb,<mongodb><import>,7,1,3.0,NaN,NaN

In [20]:
mydata['Body'] = mydata['Body'].str.strip('\n')
display(mydata)

,ID,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditorDisplayName,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate
0,927358.0,1,927386.0,NaN,29-05-2009 18:09,NaN,23348,10062790,I accidentally strongcommitted the wrong files...,89904,...,NaN,30-06-2021 05:07,05-10-2021 13:26,How do I undo the most recent local commits in...,<git><version-control><git-commit><undo>,98,10,7322.0,NaN,16-03-2013 10:08
1,2003505.0,1,2003515.0,NaN,05-01-2010 01:12,NaN,18514,9285139,I want to delete a branch both locally and rem...,95592,...,NaN,06-10-2021 22:38,06-10-2021 22:38,How do I delete a Git branch locally and remot...,<git><version-control><git-branch><git-push><g...,41,10,5727.0,NaN,NaN
2,5767325.0,1,5767357.0,NaN,23-04-2011 22:17,NaN,9931,8937271,I have an array of numbers and I'm using the c...,364969,...,NaN,21-05-2020 04:20,24-09-2021 08:51,How can I remove a specific item from an array?,<javascript><arrays>,112,5,1507.0,NaN,NaN
3,16956810.0,1,16957078.0,NaN,06-06-2013 08:06,NaN,6304,8229811,I'm trying to find a way to scan my entire Lin...,954986,...,NaN,21-05-2017 11:40,30-08-2021 13:56,How do I find all files containing specific te...,<linux><text><grep><directory><find>,53,10,3036.0,NaN,NaN
4,2906582.0,1,2906586.0,NaN,25-05-2010 16:39,NaN,2306,7805008,I would like to create an HTML button that act...,48523,...,NaN,21-04-2021 16:46,22-09-2021 19:42,How to create an HTML button that acts like a ...,<html><button><hyperlink><anchor>,37,9,503.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199996,52253192.0,1,52264568.0,NaN,10-09-2018 07:44,NaN,6,40455,"I am currently trying to figure out, how to pa...",6333935,...,NaN,10-09-2018 19:55,16-12-2020 15:47,PySpark - to_date format from column,<apache-spark><pyspark><apache-spark-sql>,3,0,1.0,NaN,NaN
199997,26151.0,1,26162.0,NaN,25-08-2008 14:47,NaN,73,40455,C++ 0x has template aliases (sometimes referre...,2759,...,Konrad Rudolph,07-08-2012 15:11,02-09-2015 04:27,Template typedefs - What's your work around?,<c++><templates><type-safety>,3,1,19.0,NaN,NaN
199998,37141516.0,1,55449823.0,NaN,10-05-2016 14:31,NaN,22,40454,"Laravel 5.2 has pretty nice Helpers, I would l...",4322159,...,NaN,NaN,28-09-2021 11:07,Laravel 5.2 pluck() multiple attributes from E...,<laravel-5.2><helpers><laravel-collection>,9,0,4.0,NaN,NaN
199999,12005526.0,1,22312983.0,NaN,17-08-2012 12:10,NaN,16,40454,I was given access to a server with 50+ php rp...,1382299,...,NaN,08-11-2016 18:11,05-04-2020 20:11,Erase multiple packages using rpm or yum,<unix><rpm><yum>,5,0,9.0,NaN,NaN
200000,11041961.0,1,NaN,NaN,14-06-2012 22:00,NaN,18,40454,I tried mongo import like this licodemongoimpo...,1052073,...,NaN,NaN,11-04-2020 19:58,Cannot import mongodb,<mongodb><import>,7,1,3.0,NaN,NaN

In [18]:
mydata['Body'] = mydata['Body'].str.replace('>', '')
display(mydata)

,ID,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,LastEditorDisplayName,LastEditDate,LastActivityDate,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate
0,927358.0,1,927386.0,NaN,29-05-2009 18:09,NaN,23348,10062790,I accidentally strongcommitted the wrong files...,89904,...,NaN,30-06-2021 05:07,05-10-2021 13:26,How do I undo the most recent local commits in...,<git><version-control><git-commit><undo>,98,10,7322.0,NaN,16-03-2013 10:08
1,2003505.0,1,2003515.0,NaN,05-01-2010 01:12,NaN,18514,9285139,I want to delete a branch both locally and rem...,95592,...,NaN,06-10-2021 22:38,06-10-2021 22:38,How do I delete a Git branch locally and remot...,<git><version-control><git-branch><git-push><g...,41,10,5727.0,NaN,NaN
2,5767325.0,1,5767357.0,NaN,23-04-2011 22:17,NaN,9931,8937271,I have an array of numbers and I'm using the c...,364969,...,NaN,21-05-2020 04:20,24-09-2021 08:51,How can I remove a specific item from an array?,<javascript><arrays>,112,5,1507.0,NaN,NaN
3,16956810.0,1,16957078.0,NaN,06-06-2013 08:06,NaN,6304,8229811,I'm trying to find a way to scan my entire Lin...,954986,...,NaN,21-05-2017 11:40,30-08-2021 13:56,How do I find all files containing specific te...,<linux><text><grep><directory><find>,53,10,3036.0,NaN,NaN
4,2906582.0,1,2906586.0,NaN,25-05-2010 16:39,NaN,2306,7805008,I would like to create an HTML button that act...,48523,...,NaN,21-04-2021 16:46,22-09-2021 19:42,How to create an HTML button that acts like a ...,<html><button><hyperlink><anchor>,37,9,503.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199996,52253192.0,1,52264568.0,NaN,10-09-2018 07:44,NaN,6,40455,"I am currently trying to figure out, how to pa...",6333935,...,NaN,10-09-2018 19:55,16-12-2020 15:47,PySpark - to_date format from column,<apache-spark><pyspark><apache-spark-sql>,3,0,1.0,NaN,NaN
199997,26151.0,1,26162.0,NaN,25-08-2008 14:47,NaN,73,40455,C++ 0x has template aliases (sometimes referre...,2759,...,Konrad Rudolph,07-08-2012 15:11,02-09-2015 04:27,Template typedefs - What's your work around?,<c++><templates><type-safety>,3,1,19.0,NaN,NaN
199998,37141516.0,1,55449823.0,NaN,10-05-2016 14:31,NaN,22,40454,"Laravel 5.2 has pretty nice Helpers, I would l...",4322159,...,NaN,NaN,28-09-2021 11:07,Laravel 5.2 pluck() multiple attributes from E...,<laravel-5.2><helpers><laravel-collection>,9,0,4.0,NaN,NaN
199999,12005526.0,1,22312983.0,NaN,17-08-2012 12:10,NaN,16,40454,I was given access to a server with 50+ php rp...,1382299,...,NaN,08-11-2016 18:11,05-04-2020 20:11,Erase multiple packages using rpm or yum,<unix><rpm><yum>,5,0,9.0,NaN,NaN
200000,11041961.0,1,NaN,NaN,14-06-2012 22:00,NaN,18,40454,I tried mongo import like this licodemongoimpo...,1052073,...,NaN,NaN,11-04-2020 19:58,Cannot import mongodb,<mongodb><import>,7,1,3.0,NaN,NaN

In [21]:

mydata.to_csv('file_name.csv', index=False)